### ISSUE TITLE
How to disable infinate scrolling?

### ISSUE THREAD

**Issue by kaumudpa** [adbonnin/flutter_carousel#1]
Is there a possibility to disable infinate scrolling?

I have a page where 4 items are a part of carousel and need to disable infinite view. How do we achieve that?

**Comment by adbonnin** [comment]
Hi @kaumudpa,

A new parameter `infiniteScroll` has been added to the controller.

An example has been updated to see this update in action :
https://adbonnin.github.io/flutter_carousel/#/scale-transition

Best regards,

**Comment by kaumudpa** [comment]
Looks Good! (y)
